language: ruby
sudo: required
services:
  - docker
cache:
  - bundler
rvm:
  - 2.3
env:
  global:
    - KITCHEN_YAML=.kitchen.docker.yml
  matrix:
    - CHEF_VERSION=12 KAFKA_VERSION=0.8.1.1 SCALA_VERSION=2.9.2 KAFKA_MD5=7541ed160f1b3aa1a5334d4e782ba4d3
    - CHEF_VERSION=12 KAFKA_VERSION=1.1.1 SCALA_VERSION=2.11 KAFKA_CTRL_SHUTDOWN=true
    - CHEF_VERSION=13 KAFKA_VERSION=1.1.1 SCALA_VERSION=2.11 KAFKA_SHA512=2bf14a07c569c84736271471a9abb7b937b311780ed2a3d969ac0123737319e9151e0a69d6b8bd309a57b92cb00a90400e8e19e0512a6ee9206b2c91826af930
    - CHEF_VERSION=13 KAFKA_VERSION=1.1.1 SCALA_VERSION=2.11 CHEF_CHANNEL=current
install: travis_wait bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
script: bundle exec kitchen test --destroy=always
matrix:
  fast_finish: true
  allow_failures:
    - env: CHEF_VERSION=13 KAFKA_VERSION=1.0.0 SCALA_VERSION=2.11 CHEF_CHANNEL=current
  include:
    - sudo: false
      env: []
      rvm: 2.3
      script: bundle exec rake test
